/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AugmentsRouteImport } from './routes/augments'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ExhibitRouteImport } from './routes/exhibit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiX402PayRouteImport } from './routes/api/x402/pay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AugmentsRoute = AugmentsRouteImport.update({
  id: '/augments',
  path: '/augments',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitRoute = ExhibitRouteImport.update({
  id: '/exhibit',
  path: '/exhibit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiX402PayRoute = ApiX402PayRouteImport.update({
  id: '/api/x402/pay',
  path: '/api/x402/pay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/console': typeof ConsoleRoute
  '/exhibit': typeof ExhibitRoute
  '/login': typeof LoginRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/x402/pay': typeof ApiX402PayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/console': typeof ConsoleRoute
  '/exhibit': typeof ExhibitRoute
  '/login': typeof LoginRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/x402/pay': typeof ApiX402PayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/console': typeof ConsoleRoute
  '/exhibit': typeof ExhibitRoute
  '/login': typeof LoginRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/x402/pay': typeof ApiX402PayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/augments'
    | '/console'
    | '/exhibit'
    | '/login'
    | '/api/avatar'
    | '/api/auth/$'
    | '/api/x402/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/augments'
    | '/console'
    | '/exhibit'
    | '/login'
    | '/api/avatar'
    | '/api/auth/$'
    | '/api/x402/pay'
  id:
    | '__root__'
    | '/'
    | '/augments'
    | '/console'
    | '/exhibit'
    | '/login'
    | '/api/avatar'
    | '/api/auth/$'
    | '/api/x402/pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AugmentsRoute: typeof AugmentsRoute
  ConsoleRoute: typeof ConsoleRoute
  ExhibitRoute: typeof ExhibitRoute
  LoginRoute: typeof LoginRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiX402PayRoute: typeof ApiX402PayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/augments': {
      id: '/augments'
      path: '/augments'
      fullPath: '/augments'
      preLoaderRoute: typeof AugmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibit': {
      id: '/exhibit'
      path: '/exhibit'
      fullPath: '/exhibit'
      preLoaderRoute: typeof ExhibitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/pay': {
      id: '/api/x402/pay'
      path: '/api/x402/pay'
      fullPath: '/api/x402/pay'
      preLoaderRoute: typeof ApiX402PayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AugmentsRoute: AugmentsRoute,
  ConsoleRoute: ConsoleRoute,
  ExhibitRoute: ExhibitRoute,
  LoginRoute: LoginRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiX402PayRoute: ApiX402PayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
