/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AugmentsRouteImport } from './routes/augments'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DojoRouteImport } from './routes/dojo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoaRouteImport } from './routes/moa'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WarpRouteImport } from './routes/warp'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiSolanaRpcRouteImport } from './routes/api/solana-rpc'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlockworksSearchRouteImport } from './routes/api/blockworks/search'
import { Route as ApiMojoBroadcastRouteImport } from './routes/api/mojo/broadcast'
import { Route as ApiMojoSignChallengeRouteImport } from './routes/api/mojo/sign-challenge'
import { Route as ApiTinyfishEnrichRouteImport } from './routes/api/tinyfish/enrich'
import { Route as ApiTinyfishSearchRouteImport } from './routes/api/tinyfish/search'
import { Route as ApiXProbeMoneyRouteImport } from './routes/api/x/probe-money'
import { Route as ApiXSocialGraphRouteImport } from './routes/api/x/social-graph'
import { Route as ApiX402PayRouteImport } from './routes/api/x402/pay'
import { Route as ApiX402StatusRouteImport } from './routes/api/x402/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AugmentsRoute = AugmentsRouteImport.update({
  id: '/augments',
  path: '/augments',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DojoRoute = DojoRouteImport.update({
  id: '/dojo',
  path: '/dojo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoaRoute = MoaRouteImport.update({
  id: '/moa',
  path: '/moa',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WarpRoute = WarpRouteImport.update({
  id: '/warp',
  path: '/warp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSolanaRpcRoute = ApiSolanaRpcRouteImport.update({
  id: '/api/solana-rpc',
  path: '/api/solana-rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlockworksSearchRoute = ApiBlockworksSearchRouteImport.update({
  id: '/api/blockworks/search',
  path: '/api/blockworks/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMojoBroadcastRoute = ApiMojoBroadcastRouteImport.update({
  id: '/api/mojo/broadcast',
  path: '/api/mojo/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMojoSignChallengeRoute = ApiMojoSignChallengeRouteImport.update({
  id: '/api/mojo/sign-challenge',
  path: '/api/mojo/sign-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTinyfishEnrichRoute = ApiTinyfishEnrichRouteImport.update({
  id: '/api/tinyfish/enrich',
  path: '/api/tinyfish/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTinyfishSearchRoute = ApiTinyfishSearchRouteImport.update({
  id: '/api/tinyfish/search',
  path: '/api/tinyfish/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXProbeMoneyRoute = ApiXProbeMoneyRouteImport.update({
  id: '/api/x/probe-money',
  path: '/api/x/probe-money',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXSocialGraphRoute = ApiXSocialGraphRouteImport.update({
  id: '/api/x/social-graph',
  path: '/api/x/social-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiX402PayRoute = ApiX402PayRouteImport.update({
  id: '/api/x402/pay',
  path: '/api/x402/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiX402StatusRoute = ApiX402StatusRouteImport.update({
  id: '/api/x402/status',
  path: '/api/x402/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/console': typeof ConsoleRoute
  '/dojo': typeof DojoRoute
  '/login': typeof LoginRoute
  '/moa': typeof MoaRoute
  '/settings': typeof SettingsRoute
  '/warp': typeof WarpRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/solana-rpc': typeof ApiSolanaRpcRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blockworks/search': typeof ApiBlockworksSearchRoute
  '/api/mojo/broadcast': typeof ApiMojoBroadcastRoute
  '/api/mojo/sign-challenge': typeof ApiMojoSignChallengeRoute
  '/api/tinyfish/enrich': typeof ApiTinyfishEnrichRoute
  '/api/tinyfish/search': typeof ApiTinyfishSearchRoute
  '/api/x/probe-money': typeof ApiXProbeMoneyRoute
  '/api/x/social-graph': typeof ApiXSocialGraphRoute
  '/api/x402/pay': typeof ApiX402PayRoute
  '/api/x402/status': typeof ApiX402StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/console': typeof ConsoleRoute
  '/dojo': typeof DojoRoute
  '/login': typeof LoginRoute
  '/moa': typeof MoaRoute
  '/settings': typeof SettingsRoute
  '/warp': typeof WarpRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/solana-rpc': typeof ApiSolanaRpcRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blockworks/search': typeof ApiBlockworksSearchRoute
  '/api/mojo/broadcast': typeof ApiMojoBroadcastRoute
  '/api/mojo/sign-challenge': typeof ApiMojoSignChallengeRoute
  '/api/tinyfish/enrich': typeof ApiTinyfishEnrichRoute
  '/api/tinyfish/search': typeof ApiTinyfishSearchRoute
  '/api/x/probe-money': typeof ApiXProbeMoneyRoute
  '/api/x/social-graph': typeof ApiXSocialGraphRoute
  '/api/x402/pay': typeof ApiX402PayRoute
  '/api/x402/status': typeof ApiX402StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/augments': typeof AugmentsRoute
  '/console': typeof ConsoleRoute
  '/dojo': typeof DojoRoute
  '/login': typeof LoginRoute
  '/moa': typeof MoaRoute
  '/settings': typeof SettingsRoute
  '/warp': typeof WarpRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/solana-rpc': typeof ApiSolanaRpcRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blockworks/search': typeof ApiBlockworksSearchRoute
  '/api/mojo/broadcast': typeof ApiMojoBroadcastRoute
  '/api/mojo/sign-challenge': typeof ApiMojoSignChallengeRoute
  '/api/tinyfish/enrich': typeof ApiTinyfishEnrichRoute
  '/api/tinyfish/search': typeof ApiTinyfishSearchRoute
  '/api/x/probe-money': typeof ApiXProbeMoneyRoute
  '/api/x/social-graph': typeof ApiXSocialGraphRoute
  '/api/x402/pay': typeof ApiX402PayRoute
  '/api/x402/status': typeof ApiX402StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/augments'
    | '/console'
    | '/dojo'
    | '/login'
    | '/moa'
    | '/settings'
    | '/warp'
    | '/api/avatar'
    | '/api/solana-rpc'
    | '/api/auth/$'
    | '/api/blockworks/search'
    | '/api/mojo/broadcast'
    | '/api/mojo/sign-challenge'
    | '/api/tinyfish/enrich'
    | '/api/tinyfish/search'
    | '/api/x/probe-money'
    | '/api/x/social-graph'
    | '/api/x402/pay'
    | '/api/x402/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/augments'
    | '/console'
    | '/dojo'
    | '/login'
    | '/moa'
    | '/settings'
    | '/warp'
    | '/api/avatar'
    | '/api/solana-rpc'
    | '/api/auth/$'
    | '/api/blockworks/search'
    | '/api/mojo/broadcast'
    | '/api/mojo/sign-challenge'
    | '/api/tinyfish/enrich'
    | '/api/tinyfish/search'
    | '/api/x/probe-money'
    | '/api/x/social-graph'
    | '/api/x402/pay'
    | '/api/x402/status'
  id:
    | '__root__'
    | '/'
    | '/augments'
    | '/console'
    | '/dojo'
    | '/login'
    | '/moa'
    | '/settings'
    | '/warp'
    | '/api/avatar'
    | '/api/solana-rpc'
    | '/api/auth/$'
    | '/api/blockworks/search'
    | '/api/mojo/broadcast'
    | '/api/mojo/sign-challenge'
    | '/api/tinyfish/enrich'
    | '/api/tinyfish/search'
    | '/api/x/probe-money'
    | '/api/x/social-graph'
    | '/api/x402/pay'
    | '/api/x402/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AugmentsRoute: typeof AugmentsRoute
  ConsoleRoute: typeof ConsoleRoute
  DojoRoute: typeof DojoRoute
  LoginRoute: typeof LoginRoute
  MoaRoute: typeof MoaRoute
  SettingsRoute: typeof SettingsRoute
  WarpRoute: typeof WarpRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiSolanaRpcRoute: typeof ApiSolanaRpcRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlockworksSearchRoute: typeof ApiBlockworksSearchRoute
  ApiMojoBroadcastRoute: typeof ApiMojoBroadcastRoute
  ApiMojoSignChallengeRoute: typeof ApiMojoSignChallengeRoute
  ApiTinyfishEnrichRoute: typeof ApiTinyfishEnrichRoute
  ApiTinyfishSearchRoute: typeof ApiTinyfishSearchRoute
  ApiXProbeMoneyRoute: typeof ApiXProbeMoneyRoute
  ApiXSocialGraphRoute: typeof ApiXSocialGraphRoute
  ApiX402PayRoute: typeof ApiX402PayRoute
  ApiX402StatusRoute: typeof ApiX402StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/augments': {
      id: '/augments'
      path: '/augments'
      fullPath: '/augments'
      preLoaderRoute: typeof AugmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dojo': {
      id: '/dojo'
      path: '/dojo'
      fullPath: '/dojo'
      preLoaderRoute: typeof DojoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moa': {
      id: '/moa'
      path: '/moa'
      fullPath: '/moa'
      preLoaderRoute: typeof MoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warp': {
      id: '/warp'
      path: '/warp'
      fullPath: '/warp'
      preLoaderRoute: typeof WarpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/solana-rpc': {
      id: '/api/solana-rpc'
      path: '/api/solana-rpc'
      fullPath: '/api/solana-rpc'
      preLoaderRoute: typeof ApiSolanaRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blockworks/search': {
      id: '/api/blockworks/search'
      path: '/api/blockworks/search'
      fullPath: '/api/blockworks/search'
      preLoaderRoute: typeof ApiBlockworksSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mojo/broadcast': {
      id: '/api/mojo/broadcast'
      path: '/api/mojo/broadcast'
      fullPath: '/api/mojo/broadcast'
      preLoaderRoute: typeof ApiMojoBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mojo/sign-challenge': {
      id: '/api/mojo/sign-challenge'
      path: '/api/mojo/sign-challenge'
      fullPath: '/api/mojo/sign-challenge'
      preLoaderRoute: typeof ApiMojoSignChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tinyfish/enrich': {
      id: '/api/tinyfish/enrich'
      path: '/api/tinyfish/enrich'
      fullPath: '/api/tinyfish/enrich'
      preLoaderRoute: typeof ApiTinyfishEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tinyfish/search': {
      id: '/api/tinyfish/search'
      path: '/api/tinyfish/search'
      fullPath: '/api/tinyfish/search'
      preLoaderRoute: typeof ApiTinyfishSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/probe-money': {
      id: '/api/x/probe-money'
      path: '/api/x/probe-money'
      fullPath: '/api/x/probe-money'
      preLoaderRoute: typeof ApiXProbeMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/social-graph': {
      id: '/api/x/social-graph'
      path: '/api/x/social-graph'
      fullPath: '/api/x/social-graph'
      preLoaderRoute: typeof ApiXSocialGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/pay': {
      id: '/api/x402/pay'
      path: '/api/x402/pay'
      fullPath: '/api/x402/pay'
      preLoaderRoute: typeof ApiX402PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/status': {
      id: '/api/x402/status'
      path: '/api/x402/status'
      fullPath: '/api/x402/status'
      preLoaderRoute: typeof ApiX402StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AugmentsRoute: AugmentsRoute,
  ConsoleRoute: ConsoleRoute,
  DojoRoute: DojoRoute,
  LoginRoute: LoginRoute,
  MoaRoute: MoaRoute,
  SettingsRoute: SettingsRoute,
  WarpRoute: WarpRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiSolanaRpcRoute: ApiSolanaRpcRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlockworksSearchRoute: ApiBlockworksSearchRoute,
  ApiMojoBroadcastRoute: ApiMojoBroadcastRoute,
  ApiMojoSignChallengeRoute: ApiMojoSignChallengeRoute,
  ApiTinyfishEnrichRoute: ApiTinyfishEnrichRoute,
  ApiTinyfishSearchRoute: ApiTinyfishSearchRoute,
  ApiXProbeMoneyRoute: ApiXProbeMoneyRoute,
  ApiXSocialGraphRoute: ApiXSocialGraphRoute,
  ApiX402PayRoute: ApiX402PayRoute,
  ApiX402StatusRoute: ApiX402StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
